on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  get_version:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Retrieve version and Changelog
      id: get_version
      run: |
        echo icloudpd_version=$(cat pyproject.toml | grep version= | cut -d'"' -f 2) >> $GITHUB_OUTPUT
        echo 'icloudpd_changelog<<EOF' >> $GITHUB_OUTPUT
        scripts/extract_releasenotes CHANGELOG.md >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Log version and Changelog
      run: |
        echo "icloudpd_version=${{steps.get_version.outputs.icloudpd_version}}"
        echo "icloudpd_changelog=${{steps.get_version.outputs.icloudpd_changelog}}"

    outputs:
      icloudpd_version: ${{steps.get_version.outputs.icloudpd_version}}
      icloudpd_changelog: ${{steps.get_version.outputs.icloudpd_changelog}}

  build_src:
    runs-on: ubuntu-22.04
    needs: [get_version]
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Dev dependencies
      run: |
        pip install -e .[dev]

    - name: Build Python Wheel
      run: |
        scripts/build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: icloudpd-${{needs.get_version.outputs.icloudpd_version}}-artifacts
        if-no-files-found: error
        path: |
          dist/icloud*.whl

  build_windows:
    runs-on: windows-2019
    needs: [get_version]
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Dev dependencies
      run: |
        pip install -e .[dev]

    - name: Build Release Executables
      run: |
        scripts/build_bin_windows ${{needs.get_version.outputs.icloudpd_version}} amd64

    - name: Build Python Binary Wheel
      run: |
        scripts/build_binary_dist_windows ${{needs.get_version.outputs.icloudpd_version}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: icloudpd-${{needs.get_version.outputs.icloudpd_version}}-artifacts
        if-no-files-found: error
        path: |
          dist/icloud*
 
  release:
    needs: [get_version,build_src,build_windows]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: icloudpd-${{needs.get_version.outputs.icloudpd_version}}-artifacts
          path: |
            dist

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
